package chat.stoat.ui.theme

import androidx.compose.ui.graphics.Color

// Chat THT — crimson/dark theme palette
object Colour {
    val Seed = Color(0xFFD32020)

    // Light scheme — warm red primary
    val PrimaryLight = Color(0xFFB71C1C)
    val OnPrimaryLight = Color(0xFFFFFFFF)
    val PrimaryContainerLight = Color(0xFFFFCDD2)
    val OnPrimaryContainerLight = Color(0xFF7F0000)
    val InversePrimaryLight = Color(0xFFFF8A80)
    val SecondaryLight = Color(0xFF795548)
    val OnSecondaryLight = Color(0xFFFFFFFF)
    val SecondaryContainerLight = Color(0xFFD7CCC8)
    val OnSecondaryContainerLight = Color(0xFF4E342E)
    val TertiaryLight = Color(0xFF5D4037)
    val OnTertiaryLight = Color(0xFFFFFFFF)
    val TertiaryContainerLight = Color(0xFFEFEBE9)
    val OnTertiaryContainerLight = Color(0xFF3E2723)
    val BackgroundLight = Color(0xFFFFF8F7)
    val OnBackgroundLight = Color(0xFF231717)
    val SurfaceLight = Color(0xFFFFF8F7)
    val OnSurfaceLight = Color(0xFF231717)
    val SurfaceVariantLight = Color(0xFFF5DDDA)
    val OnSurfaceVariantLight = Color(0xFF534341)
    val SurfaceTintLight = Color(0xFFB71C1C)
    val InverseSurfaceLight = Color(0xFF392B2B)
    val InverseOnSurfaceLight = Color(0xFFFFEDEB)
    val ErrorLight = Color(0xFFBA1A1A)
    val OnErrorLight = Color(0xFFFFFFFF)
    val ErrorContainerLight = Color(0xFFFFDAD6)
    val OnErrorContainerLight = Color(0xFF93000A)
    val OutlineLight = Color(0xFF857371)
    val OutlineVariantLight = Color(0xFFD8C2BF)
    val ScrimLight = Color(0xFF000000)
    val SurfaceBrightLight = Color(0xFFFFF8F7)
    val SurfaceContainerLight = Color(0xFFF8ECEA)
    val SurfaceContainerHighLight = Color(0xFFF2E7E4)
    val SurfaceContainerHighestLight = Color(0xFFECE1DF)
    val SurfaceContainerLowLight = Color(0xFFFEF2EF)
    val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
    val SurfaceDimLight = Color(0xFFE8D6D4)
    val ShadowLight = Color(0xFF000000)
    val ControlActivatedLight = Color(0xFFFFCDD2)
    val ControlNormalLight = Color(0xFF534341)
    val ControlHighlightLight = Color(0x1F000000)
    val TextPrimaryInverseLight = Color(0xFFECE1DF)
    val TextSecondaryAndTertiaryInverseLight = Color(0xFFD8C2BF)
    val TextPrimaryInverseDisableOnlyLight = Color(0xFFECE1DF)
    val TextSecondaryAndTertiaryInverseDisabledLight = Color(0xFFECE1DF)
    val TextHintInverseLight = Color(0xFFECE1DF)

    // Dark scheme — deep crimson on near-black
    val PrimaryDark = Color(0xFFFF8A80)
    val OnPrimaryDark = Color(0xFF7F0000)
    val PrimaryContainerDark = Color(0xFF9B1313)
    val OnPrimaryContainerDark = Color(0xFFFFCDD2)
    val InversePrimaryDark = Color(0xFFB71C1C)
    val SecondaryDark = Color(0xFFBCAAA4)
    val OnSecondaryDark = Color(0xFF3E2723)
    val SecondaryContainerDark = Color(0xFF5D4037)
    val OnSecondaryContainerDark = Color(0xFFD7CCC8)
    val TertiaryDark = Color(0xFFA1887F)
    val OnTertiaryDark = Color(0xFF3E2723)
    val TertiaryContainerDark = Color(0xFF4E342E)
    val OnTertiaryContainerDark = Color(0xFFEFEBE9)
    val BackgroundDark = Color(0xFF0D0D12)
    val OnBackgroundDark = Color(0xFFECE1DF)
    val SurfaceDark = Color(0xFF0D0D12)
    val OnSurfaceDark = Color(0xFFECE1DF)
    val SurfaceVariantDark = Color(0xFF534341)
    val OnSurfaceVariantDark = Color(0xFFD8C2BF)
    val SurfaceTintDark = Color(0xFFFF8A80)
    val InverseSurfaceDark = Color(0xFFECE1DF)
    val InverseOnSurfaceDark = Color(0xFF392B2B)
    val ErrorDark = Color(0xFFFFB4AB)
    val OnErrorDark = Color(0xFF690005)
    val ErrorContainerDark = Color(0xFF93000A)
    val OnErrorContainerDark = Color(0xFFFFDAD6)
    val OutlineDark = Color(0xFFA08C8A)
    val OutlineVariantDark = Color(0xFF534341)
    val ScrimDark = Color(0xFF000000)
    val SurfaceBrightDark = Color(0xFF422D2D)
    val SurfaceContainerDark = Color(0xFF1C1212)
    val SurfaceContainerHighDark = Color(0xFF261C1C)
    val SurfaceContainerHighestDark = Color(0xFF312626)
    val SurfaceContainerLowDark = Color(0xFF160E0E)
    val SurfaceContainerLowestDark = Color(0xFF070707)
    val SurfaceDimDark = Color(0xFF0D0D12)
    val ShadowDark = Color(0xFF000000)
    val ControlActivatedDark = Color(0xFF9B1313)
    val ControlNormalDark = Color(0xFFD8C2BF)
    val ControlHighlightDark = Color(0x33FFFFFF)
    val TextPrimaryInverseDark = Color(0xFF231717)
    val TextSecondaryAndTertiaryInverseDark = Color(0xFF534341)
    val TextPrimaryInverseDisableOnlyDark = Color(0xFF231717)
    val TextSecondaryAndTertiaryInverseDisabledDark = Color(0xFF231717)
    val TextHintInverseDark = Color(0xFF231717)

    val PrimaryFixed = Color(0xFFFFCDD2)
    val PrimaryFixedDim = Color(0xFFFF8A80)
    val OnPrimaryFixed = Color(0xFF3F0000)
    val OnPrimaryFixedVariant = Color(0xFF7F0000)
    val SecondaryFixed = Color(0xFFD7CCC8)
    val SecondaryFixedDim = Color(0xFFBCAAA4)
    val OnSecondaryFixed = Color(0xFF2C1712)
    val OnSecondaryFixedVariant = Color(0xFF4E342E)
    val TertiaryFixed = Color(0xFFEFEBE9)
    val TertiaryFixedDim = Color(0xFFA1887F)
    val OnTertiaryFixed = Color(0xFF1A0F0C)
    val OnTertiaryFixedVariant = Color(0xFF3E2723)
    val PrimaryPaletteKeyColor = Color(0xFFD32020)
    val SecondaryPaletteKeyColor = Color(0xFF8D6E63)
    val TertiaryPaletteKeyColor = Color(0xFF795548)
    val NeutralPaletteKeyColor = Color(0xFF7A6665)
    val NeutralVariantPaletteKeyColor = Color(0xFF857371)
    val ErrorPaletteKeyColor = Color(0xFFDE3730)
}
